# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pMSW0Epd_7AL2nnLFFW1oGmQD6F1wnbJ
"""

from numpy import linalg as LNG 
import numpy as np
# Reading co-ordinates
x1 = 2
y1 = 3
x2 = 5
y2 = 7

# Calculating distance
d = ( (x2-x1)**2 + (y2-y1)**2 ) ** 0.5

# Displaying result
print('Distance = %f' %(d))